<?php


namespace App\Views;

use App\App;
use App\Users\User;
use Core\View;

class Nav extends View
{
    public function __construct($data = [])
    {
        $user = App::$session->getUser();

        if ($user) {
            switch ($user->getRole()) {
                case User::ROLE_USER:
                    $data = $this->getUserNavigation();
                    break;

                case User::ROLE_ADMIN:
                    $data = $this->getAdminNavigation();
                    break;
            }
        } else {
            $data = $this->getAnonymousNavigation();
        }

        parent::__construct($data);
    }

    public function render(string $template_path = ROOT . '/app/templates/nav.php')
    {
        return parent::render($template_path); // TODO: Change the autogenerated stub
    }

    public function getUserNavigation()
    {
        return [
            [
                'link' => '/cart.php',
                'name' => 'Cart'
            ],
            [
                'link' => '/orders/index.php',
                'name' => 'Orders'
            ],
            [
                'link' => '/index.php',
                'name' => 'Catalog'
            ],
            [
                'link' => '/logout.php',
                'name' => 'Log Out'
            ]
        ];

    }

    public function getAdminNavigation()
    {
        return [
            [
                'link' => '/admin/products/add.php',
                'name' => 'Add Product'
            ],
            [
                'link' => '/admin/products/view.php',
                'name' => 'View Products'
            ],
            [
                'link' => '/admin/orders/index.php',
                'name' => 'View orders'
            ],
            [
                'link' => '/index.php',
                'name' => 'Catalog'
            ],
            [
                'link' => '/logout.php',
                'name' => 'Log Out',
                'class' => 'log_out'
            ]
        ];

    }

    public function getAnonymousNavigation()
    {
        return [
            [
                'link' => '/login.php',
                'name' => 'Login'
            ],
            [
                'link' => '/index.php',
                'name' => 'Catalog'
            ],
            [
                'link' => '/register.php',
                'name' => 'Register'
            ]
        ];

    }
}
