<?php


namespace Core\Views;


use Core\View;

class Catalog extends View
{
    public function render($template_path = ROOT . '/app/templates/catalog.tpl.php')
    {
        return parent::render($template_path); // TODO: Change the autogenerated stub
    }
}