<?php


namespace Core\Views;

use Core\View;

class Nav extends View
{
    public function render($template_path = ROOT . '/app/templates/nav.php')
    {
        return parent::render($template_path); // TODO: Change the autogenerated stub
    }
}
